### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by solaolateju** [graasp/graasp-app-timer#4]
Translation
![Screenshot 2020-04-10 at 10 34 09](https://user-images.githubusercontent.com/18397749/78976648-e46bfa00-7b16-11ea-9572-ce0cc11a0e87.png)

**Comment by juancarlosfarah** [comment]
@solaolateju, you can close this. When you close, you can mention the commit that it is closed by as a comment. The ID of the commit is a long hexadecimal string and can be found by running `git log`.

**Comment by juancarlosfarah** [comment]
I will do it as an example for this issue.

Added in bee8c851f979d7efee59772abb3d7c9596be1010.
